version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/proofs"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/tools"
    schedule:
      interval: "monthly"
