export enum Paths {
  ROOT = "/",
  HOME = "/home",
  IDENTITY = "/identity/:id",
  CREATE_IDENTITY = "/create-identity",
  REVEAL_IDENTITY_COMMITMENT = "/reveal-identity-commitment",
  LOGIN = "/login",
  ONBOARDING = "/onboarding",
  ONBOARDING_BACKUP = "/onboarding-backup",
  GENERATE_MNEMONIC = "/generate-mnemonic",
  REVEAL_MNEMONIC = "/reveal-mnemonic",
  REQUESTS = "/requests",
  SETTINGS = "/settings",
  DOWNLOAD_BACKUP = "/download-backup",
  UPLOAD_BACKUP = "/upload-backup",
  CONNECT_IDENTITY = "/connect-identity",
  RECOVER = "/recover",
  RESET_PASSWORD = "/reset-password",
  ADD_VERIFIABLE_CREDENTIAL = "/add-verifiable-credential",
  GENERATE_VERIFIABLE_PRESENTATION = "/generate-verifiable-presentation",
  JOIN_GROUP = "/groups/join",
  GROUP_MERKLE_PROOF = "/groups/merkle-proof",
}
