export enum Paths {
  ROOT = "/",
  HOME = "/home",
  CREATE_IDENTITY = "/create-identity",
  LOGIN = "/login",
  ONBOARDING = "/onboarding",
  GENERATE_MNEMONIC = "/generate-mnemonic",
  REVEAL_MNEMONIC = "/reveal-mnemonic",
  REQUESTS = "/requests",
  SETTINGS = "/settings",
  DOWNLOAD_BACKUP = "/download-backup",
  CONNECT_IDENTITY = "/connect-identity",
  RECOVER = "/recover",
  RESET_PASSWORD = "/reset-password",
}
