/* eslint "@typescript-eslint/no-explicit-any": 0 */
/* eslint "@typescript-eslint/no-unused-vars": 0 */

/** Declaration file generated by dts-gen */

export = snarkjs // eslint-disable-line @typescript-eslint/no-use-before-define

declare const snarkjs: {
  groth16: {
    exportSolidityCallData: any;
    fullProve(_input: any, wasmFile: any, zkeyFileName: any, logger?: any): Promise<any>;
    prove(zkeyFileName: any, witnessFileName: any, logger?: any): Promise<any>;
    verify(_vk_verifier: any, _publicSignals: any, _proof: any, logger?: any): Promise<any>;
  };
  plonk: {
    exportSolidityCallData: any;
    fullProve: any;
    prove: any;
    setup: any;
    verify: any;
  };
  powersOfTau: {
    beacon: any;
    challengeContribute: any;
    contribute: any;
    convert: any;
    exportChallenge: any;
    exportJson: any;
    importResponse: any;
    newAccumulator: any;
    preparePhase2: any;
    truncate: any;
    verify: any;
  };
  r1cs: {
    exportJson: any;
    info: any;
    print: any;
  };
  wtns: {
    calculate: any;
    debug: any;
    exportJson: any;
  };
  zKey: {
    beacon: any;
    bellmanContribute: any;
    contribute: any;
    exportBellman: any;
    exportJson: any;
    exportSolidityVerifier: any;
    exportVerificationKey: any;
    importBellman: any;
    newZKey: any;
    verifyFromInit: any;
    verifyFromR1cs: any;
  };
}

