name: Deploy demo
on:
  push:
    branches: [main]
    paths:
      - "packages/demo/**"
      - "packages/merkle-mock-server/**"

  workflow_dispatch:
    inputs:
      build:
        description: "Build trigger"
        required: true
        default: "enable"
        type: choice
        options:
        - enable
        - disable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:  
  deploy:
    runs-on: ubuntu-22.04

    env:
      DATA: ${{ github.event.inputs.build || 'enable' }}
    permissions:
      id-token: write
      contents: read
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::490752553772:role/crypt-keeper-extension-ecs-deploy-slc
          role-duration-seconds: 1800
          aws-region: eu-central-1

      - name: Build and Push images to ECR
        run: |
          .github/scripts/build.sh ${{ env.DATA }}

      - name: Create Deployment
        run: |
          .github/scripts/deploy.sh
