name: E2E
on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * *" # run every day at 9:00 UTC

  push:
    branches: master
  pull_request:
    branches: master

env:
  CRYPTKEEPER_DEBUG: false
  RANDOM_IDENTITY: false
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]
        command: ["e2e"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Setup demo
        working-directory: ./demo
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Run Playwright tests
        run: npm run ${{ matrix.command }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
