name: Publish packages

on:
  push:
    tags:
      - "@cryptkeeperzk/providers-*"

env:
  CRYPTKEEPER_DEBUG: false
  INTERREP_IDENTITY: false
  USER_MNEMONIC: false
  E2E: false
  METAMASK_EXTENSION_ID: "nkbihfbeogaeaoehlefnkodbefgpgknn"
  METAMASK_VERSION: "10.28.1"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}
  TARGET: "chrome"
  DEMO_URL: ${{ vars.DEMO_URL }}
  PROVIDERS_VERSION: ""
  MANIFEST_VERSION: 3
  VERIFIABLE_CREDENTIALS: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-packages:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Get versions
        run: |-
          echo "PROVIDERS_VERSION=$(node -e "console.log(require('./packages/providers/package.json').version)")" >> $GITHUB_ENV

      - run: |-
          pnpm run build
          zip -r cryptkeeper-providers-v${{ env.PROVIDERS_VERSION }}.zip ./packages/providers/dist

      - name: Setup publisher
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          pnpm config set commit-hooks false
          pnpm config set git-checks false 
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      
      - name: Sign @cryptkeeperzk/providers
        if: startsWith(github.ref_name, '@cryptkeeperzk/providers-') == true
        run: |-
          export GPG_TTY=`tty`
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --passphrase "$GPG_SIGNING_KEY_PASSPHRASE" --batch --pinentry-mode loopback --import
          gpg --passphrase $GPG_SIGNING_KEY_PASSPHRASE --batch --pinentry-mode loopback --detach-sign --armor cryptkeeper-providers-v${{ env.PROVIDERS_VERSION }}.zip
          echo $(shasum cryptkeeper-providers-v${{ env.PROVIDERS_VERSION }}.zip | awk '{ print $1 }') >> cryptkeeper-providers-checksum-v${{ env.PROVIDERS_VERSION }}.txt
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_KEY_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}

      - name: Publish packages
        run: pnpm run publish:packages -- --access=public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload @cryptkeeperzk/providers
        if: startsWith(github.ref_name, '@cryptkeeperzk/providers-') == true
        run: |-
          gh release upload "${{ github.ref_name }}" "cryptkeeper-providers-v${{ env.PROVIDERS_VERSION }}.zip" "cryptkeeper-providers-checksum-v${{ env.PROVIDERS_VERSION }}.txt" "cryptkeeper-providers-v${{ env.PROVIDERS_VERSION }}.zip.asc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
