name: Publish chrome extension

on:
  push:
    tags:
      - "@cryptkeeperzk/app-*"

env:
  CRYPTKEEPER_DEBUG: false
  USER_MNEMONIC: false
  E2E: false
  METAMASK_EXTENSION_ID: "nkbihfbeogaeaoehlefnkodbefgpgknn"
  METAMASK_VERSION: "10.28.1"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}
  BANDADA_API_URL: ${{ vars.BANDADA_API_URL }}
  BANDADA_URL: ${{ vars.BANDADA_URL }}
  TARGET: "chrome"
  DEMO_URL: ${{ vars.DEMO_URL }}
  MERKLE_MOCK_SERVER: ${{ vars.MERKLE_MOCK_SERVER }}
  EXTENSION_VERSION: ""
  MANIFEST_VERSION: 3
  VERIFIABLE_CREDENTIALS: false
  WEBPACK_ANALYZER: false
  TEST_GROUP_ID: ${{ vars.TEST_GROUP_ID }}
  TEST_GROUP_API_KEY: ${{ vars.TEST_GROUP_API_KEY }}
  TEST_GROUP_INVITE_CODE: ${{ vars.TEST_GROUP_INVITE_CODE }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-chrome-extension:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: |-
          pnpm install --frozen-lockfile --prefer-offline
          pnpm install -g chrome-webstore-upload-cli

      - name: Get version
        run: |-
          echo "EXTENSION_VERSION=$(node -e "console.log('${{ github.ref_name }}'.split('-')[1])")" >> $GITHUB_ENV

      - name: Build chrome artifact
        env:
          TARGET: "chrome"
          MANIFEST_VERSION: 3
        run: |-
          pnpm exec nx run @cryptkeeperzk/app:bump --tag=${{ github.ref_name }}
          pnpm run build
          zip -r cryptkeeper-chrome-extension-v${{ env.EXTENSION_VERSION }}.zip ./packages/app/dist

      - name: Upload artifact to chrome store
        run: |-
          chrome-webstore-upload upload --source cryptkeeper-chrome-extension-v${{ env.EXTENSION_VERSION }}.zip --extension-id ${{ vars.CHROME_EXTENSION_ID }} --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }} --auto-publish
