name: Publish firefox extension

on:
  push:
    tags:
      - "@cryptkeeperzk/app-*"

env:
  CRYPTKEEPER_DEBUG: false
  INTEREP_IDENTITY: false
  USER_MNEMONIC: false
  E2E: false
  METAMASK_EXTENSION_ID: "webextension@metamask.io"
  METAMASK_VERSION: "10.28.1"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}
  BANDADA_API_URL: ${{ vars.BANDADA_API_URL }}
  TARGET: "firefox"
  DEMO_URL: ${{ vars.DEMO_URL }}
  EXTENSION_VERSION: ""
  MANIFEST_VERSION: 2
  VERIFIABLE_CREDENTIALS: false
  WEBPACK_ANALYZER: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-firefox-extension:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: |-
          pnpm install --frozen-lockfile --prefer-offline
          pnpm install -g web-ext web-ext-submit

      - name: Get version
        run: |-
          echo "EXTENSION_VERSION=$(node -e "console.log('${{ github.ref_name }}'.split('-')[1])")" >> $GITHUB_ENV

      - name: Build firefox artifact
        env:
          TARGET: "firefox"
          MANIFEST_VERSION: 2
        run: |-
          pnpm exec nx run @cryptkeeperzk/app:bump --tag=${{ github.ref_name }}
          pnpm run build
          zip -r cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip ./packages/app/dist

      - name: Sign build
        run: |-
          export GPG_TTY=`tty`
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --passphrase "$GPG_SIGNING_KEY_PASSPHRASE" --batch --pinentry-mode loopback --import
          gpg --passphrase $GPG_SIGNING_KEY_PASSPHRASE --batch --pinentry-mode loopback --detach-sign --armor cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip
          echo $(shasum cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip | awk '{ print $1 }') >> cryptkeeper-firefox-extension-checksum-v${{ env.EXTENSION_VERSION }}.txt
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_KEY_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}

      - name: Upload artifact to firefox store
        run: |-
          mv cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip ./packages/app/dist
          cd ./packages/app/dist
          web-ext-submit --api-key=${{ secrets.WEB_EXT_API_KEY }} --api-secret=${{ secrets.WEB_EXT_API_SECRET }} --use-submission-api --channel=listed
          cd ../../..

      - name: Upload build
        run: |-
          gh release upload "${{ github.ref_name }}" "./packages/app/dist/cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip" "cryptkeeper-firefox-extension-checksum-v${{ env.EXTENSION_VERSION }}.txt" "cryptkeeper-firefox-extension-v${{ env.EXTENSION_VERSION }}.zip.asc"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
