name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  CRYPTKEEPER_DEBUG: false
  INTEREP_IDENTITY: false
  USER_MNEMONIC: false
  E2E: false
  METAMASK_EXTENSION_ID: "nkbihfbeogaeaoehlefnkodbefgpgknn"
  METAMASK_VERSION: "10.28.1"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}
  BANDADA_API_URL: ${{ vars.BANDADA_API_URL }}
  TARGET: "chrome"
  DEMO_URL: ${{ vars.DEMO_URL }}
  MERKLE_MOCK_SERVER: ${{ vars.MERKLE_MOCK_SERVER }}
  EXTENSION_VERSION: ""
  MANIFEST_VERSION: 3
  VERIFIABLE_CREDENTIALS: false
  WEBPACK_ANALYZER: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Import GPG key
        run: |-
          export GPG_TTY=`tty`
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --passphrase "$GPG_SIGNING_KEY_PASSPHRASE" --batch --pinentry-mode loopback --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_KEY_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}

      - name: Setup git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm config set commit-hooks false
          # TODO: support commit signing when it's supported https://github.com/jscutlery/semver/issues/489
          # git config commit.gpgsign true
          # git config user.signingkey $GPG_SIGNING_KEY_ID
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        env:
          GPG_SIGNING_KEY_ID: ${{ secrets.GPG_SIGNING_KEY_ID }}

      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Release
        run: |-
          pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
