name: Release

on:
  workflow_dispatch:

env:
  CRYPTKEEPER_DEBUG: false
  INTERREP_IDENTITY: false
  USER_MNEMONIC: false
  E2E: false
  METAMASK_EXTENSION_ID: "nkbihfbeogaeaoehlefnkodbefgpgknn"
  METAMASK_VERSION: "10.28.1"
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  FREIGHT_TRUST_NETWORK: ${{ secrets.FREIGHT_TRUST_NETWORK }}
  PULSECHAIN_API_KEY: ${{ secrets.PULSECHAIN_API_KEY }}
  TARGET: "chrome"
  DEMO_URL: ${{ vars.DEMO_URL }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Setup publisher
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm config set commit-hooks false
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - run: pnpm install --frozen-lockfile --prefer-offline

      - name: Version
        run: pnpm run release -- --base=last-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag last-release
        run: |
          git tag -f last-release
          git push origin last-release --force

  build-chrome-extension:
    needs: release

    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: |-
          pnpm install --frozen-lockfile --prefer-offline
          pnpm install -g chrome-webstore-upload-cli

      - name: Build artifact
        run: |-
          pnpm run build
          zip -r chrome-extension-${{ github.ref }}.zip ./packanges/app/dist

      - name: Upload artifact
        run: |-
          chrome-webstore-upload upload \\
            --source chrome-extension-${{ github.ref }}.zip \\
            --extension-id ${{ vars.EXTENSION_ID }} \\
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \\
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \\
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
